### ISSUE TITLE
Cannot find module 'timers' - bluebird

### ISSUE THREAD

**Issue by daniandl** [sibnerian/electron-promise-ipc#14]
Can't use this lib sadly, this shows up in renderer process:

![image](https://user-images.githubusercontent.com/2960785/66306579-4cd8e500-e902-11e9-8c44-56214ac97e97.png)

Tried installing package from pull #13 but it just said the dependency can't be found.

**Comment by sibnerian** [comment]
I've published a new version 1.6.0 that does not include bluebird - can you try it?

**Comment by daniandl** [comment]
Error is gone, LGTM 🙂
