### ISSUE TITLE
Can't use in Main Process for emit data

### ISSUE THREAD

**Issue by pranavwani** [sibnerian/electron-promise-ipc#19]
Cant emit data from the main process. Throwing below error,
`TypeError: Cannot read property 'apply' of undefined`

```
const ipc = require('electron-promise-ipc')

ipc
  .send('getRendererData', {})
  .then((rendererData) => console.log(rendererData))
  .catch((e) => console.error(e));
```

Can listen from the main process, send from the renderer process.

**Comment by sibnerian** [comment]
I notice you’re using require() and not import so I’m guessing that’s the
error. What version are you on? In 2.0.0, we switched to commonJS exports.

I bet that this would be solved by using:

const ipc = require('electron-promise-ipc').default;

**Comment by pranavwani** [comment]
Sorry for raising an issue without reading the doc properly. Actually I have a query for sending data from the main process to the renderer process. In doc mention that using WebContent, you can send info. from the main process to the renderer will you please guide for it.

**Comment by sibnerian** [comment]
Let’s refer to the documentation.

You can also send data from the main process to a renderer, if you pass in
its WebContents <http://electron.atom.io/docs/api/web-contents> object.

// in main processimport promiseIpc from 'electron-promise-ipc';

promiseIpc
  .send('getRendererData', webContentsForRenderer)
  .then((rendererData) => console.log(rendererData))
  .catch((e) => console.error(e));
// in rendererimport promiseIpc from 'electron-promise-ipc';
promiseIpc.on('getRendererData', (event) => {
  return getSomeSuperAwesomeRendererData();
});

How to obtain the webContents is up to you!  It depends on your app and use
case. The electron documentation is good to read.

One suggestion would be to send a message from the renderer as soon as it
loads, and save the value of event.sender.
