### ISSUE TITLE
Improve for unify renderer.js and mainProcess.js

### ISSUE THREAD

**Issue by tmirun** [sibnerian/electron-promise-ipc#2]
Hi Guy,
In first of all, i want to say GOOD JOB for this library!
i created a similar service for my project, but i think your code is better =)

i was seeing the code,  renderer.js and mainProcess.js is the same, i think we can unify the both code, pass ipcContext (ipcRederer or Main) as constructor param.

![image](https://user-images.githubusercontent.com/8052536/43951907-b4c7b7ce-9c94-11e8-8c7c-eec5d0e6e31a.png)

And export it dependent if is in Renderer or main process

``` javascript
if (isRenderer) {
  module.exports = new PromiseIpc(require('window.require('electron').ipcRenderer'), options);
} else {
  module.exports = new PromiseIpc(require('require('electron').ipcMain'), options);
}
```

do you think it's viable?

**Comment by sibnerian** [comment]
Hi @tmirun! Thank you for the kind words, I'm glad you like the package.

Thanks for your suggestion. I am always in favor of refactoring and DRY code! However, there's a small detail that could make this tricky. If you examine [mainProcess.js](https://github.com/sibnerian/electron-promise-ipc/blob/master/src/mainProcess.js#L12) you'll see that _the method signature for `send` takes an extra argument_. Unlike in the renderer process, you need a `webContents` object to call `send`. See also: http://electron.atom.io/docs/api/ipc-main/. And you'll notice that this requirement causes code differences in a few more places, as well. Like in the renderer we can call `ipcRenderer.send` (in the 'on' method) but in the main process we need to use `event.sender.send`.

If I were going to refactor this, I'd take a different approach - probably create a parent class `PromiseIpcBase` and have the two existing classes inherit from it. You could create 'generic' versions of the on/send methods and then have the child classes call those. The nice thing is the API would stay the same and you wouldn't even need to change any tests =)

I don't know when I'd have time to look at this, but if you want to have a go at it, I'd be glad to accept a PR!

**Comment by sibnerian** [comment]
I just did this so will close the issue.
