### ISSUE TITLE
Error when node integration is set to false

### ISSUE THREAD

**Issue by lichaar** [sibnerian/electron-promise-ipc#26]
It seems you can't import promiseIpc into the renderer process if node integration is set to false, If so you'll face the following error:

`Uncaught ReferenceError: require is not defined`

Since enabling node integration has its own security issues, Shouldn't this work without needing to enable that?

**Comment by sibnerian** [comment]
Happy to take a PR to resolve this!

**Comment by sibnerian** [comment]
Looks like if `nodeIntegration` is false, you need to use `preload` if you want to require _anything_ in the renderer. Including electron.

I've added some docs on how to do this, published a preload script which you can use (by requiring it from your own preload) , and verified that this works on the newest version of Electron.

Cheers!
