### ISSUE TITLE
Is there any way (or even reason) to use an async function within a Promised handler?

### ISSUE THREAD

**Issue by Keagel** [sibnerian/electron-promise-ipc#27]
First of all, thank you for this module, this is exactly what I wanted.

Nevertheless, I encountered a problem when using a Promise on a handler that spawns a dialog asynchronously.

`background.js`
```js
import {dialog} from 'electron'
promiseIpc.on('openDialog', (options) => {
  dialog
      .showOpenDialog(win, options)
      .then(r => {
        return r
      })
      .catch(e => {
        return e
      })
})
```

`mixin.js`
```js
export const mixin = {
  methods: {
    openPickerDialog({target}) {
      [...]
      window.api
          .send('openDialog', options)
          .then((results) => {
            console.log(results)
          })
          .catch((e) => {
            console.error(e)
          })
    }
  },
}
```

What happens is that the line `console.log(results)` prints `undefined` right as the message is sent, simply because the dialog is spawned asynchronously. Of course this works:

`background.js`
```js
promiseIpc.on('openDialog', (options) => {
  return dialog.showOpenDialogSync(win, options)
})
```

Is there any way (or even reason) to use Promises within a Promised handler? I'm converting my code to promiseIpc and I have quite a few handlers that make use of async functions.

**Comment by sibnerian** [comment]
Return the result of the dialog, which is a promise. The result of the promise will be sent to the other process. Your then block is redundant, and you don't need to catch/throw -- errors are passed to the other process. 

```
import {dialog} from 'electron'
promiseIpc.on('openDialog', (options) => {
  // Note the return here.
  return dialog.showOpenDialog(win, options);
})
```
